# Generated by Django 5.0.6 on 2024-06-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.AddField(
            model_name='acc_holder',
            name='date_field',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acc_holder',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='acc_holder',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='acc_holder',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='acc_holder',
            name='rate_change',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
